sstate: Make image cache imagetype-specific
Building of isar-image-base for targets qemuamd64-buster-tgz and
qemuamd64-buster-cpiogz with one bitbake call fails with:

ERROR: mc:qemuamd64-buster-tgz:isar-image-base-1.0-r0 do_rootfs: Package already staged

This is caused by sstate cache conflict for those two packages.
We need to add image type to sstate manifest data to fix the issue.

Signed-off-by: Anton Mikanovich <amikan@ilbers.de>